apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/emayssatware/helloworld-python
        env:
        - name: TARGET
          value: "from Emmanuel (Python Sample v1)"
